end-4/dots-hyprland

.config/eww/scripts/allappnames.cpp

Prevent allappnames from failing if directory its looking for doesn't exists

Update allappnames, prevent failure for invalid locations 

---

.config/eww/css/_bottomsheet.scss
.config/eww/scripts/colorgen
.config/eww/scripts/custom_configs/cava
.config/eww/scripts/mcover_rgba.py
.config/eww/scripts/music
.config/eww/windows/bottomsheet.yuck

better bottomsheet

---

install.sh

Added really basic error handling to the shell script, and edited it to clear the terminal it's running on after every stage of the install.

Illogical impulse

---

uninstall.sh

Added uninstall script to undo all changes done to the system after running install.sh, removes all installed yay packages and their dependencies, and ags.
yes, it removes the user from video/input groups as well.

Uninstall Script

---

.config/swaylock/config

Tried to follow colors and general themes used in illogical-impulse

Add config for swaylock

---

.config/hypr/hyprland.conf
.config/hypr/rules.conf

reactor: extract window and layer rules to seperate file

---

install.sh

There's a bug in my previous PR, leading to exiting when ags is not installed.
I'm sorry that I didn't tested out previously.
This PR fixes it.
Also some minor fixes.

Fixes on installation script.

---

checkdeps.sh
install.sh
scriptdata/dependencies.txt
scriptdata/functions
scriptdata/installers
update-ags.sh

- Fix yay reporting package not found (because the package names with spaces were taken as a sole package name) when use flag `-f`.
- Fix hyprland sometimes reporting error about `colors.conf` not found when it actually exists because hyprland did not reload fully.
- Split functions (basic) and installer functions into `scriptdata/` and also move `dependencies.txt` into it.
- Provide `update-ags.sh` to only update ags (since it frequently needs update).
- Minor improvements (eg. join two lines of `usermod` into one line).
- Add `checkdeps.sh` for <https://github.com/end-4/dots-hyprland/discussions/204>
This is also a preparation for future, see `TODO` comments in <https://github.com/clsty/dots-hyprarch/blob/main/utils.sh>

Severl fixes and improvement on installation script.

---

.config/ags/widgets/bar/music.js
.config/ags/widgets/desktopbackground/system.js

https://github.com/end-4/dots-hyprland/issues/225
this checks if swap is null and avoids dividing by zero

use case no swap, no zram

---

.config/hypr/keybinds.conf

This is my first time contribution so if i did something wrong please tell me. :pray:
* fixed a typo that make thunar not showing up. (missing + sign)
PS. I was about to open issue but after I googled it said if you know how to fix, it is better to do pull request so i go through pull request tutorial :face_in_clouds:

Added missing plus(+) sign

---

README.md

Fix link to wiki.

---

install.sh

Fix https://github.com/end-4/dots-hyprland/issues/260 by adding 'try' before hyprctl.

Fix #260 by adding 'try'

---

.config/ags/modules/session/sessionscreen.js

Change swaylock to hyprlock in session window

Fix: Change swaylock to hyprlock in session window

---

.config/ags/scripts/color_generation/colorgen.sh
.config/ags/scripts/color_generation/generate_colors_material.py

Fix switching schemes (after changing music), the color is taken from the music coverart rather than the wallpaper.

Scheme color dependent on music coverart

---

.config/ags/modules/.configuration/user_options.js
.config/ags/modules/sideleft/apis/gemini.js
.config/ags/services/gemini.js

For gemini memory

---

.config/ags/modules/.configuration/user_options.js
.config/ags/services/gemini.js
.config/ags/services/gpt.js

I checked it out in Gemini, works fine.

Added proxy url setting in user options

---

.config/ags/modules/sideright/quicktoggles.js
.config/hypr/hyprland/execs.conf
scriptdata/dependencies.conf

wlsunset doesn't work w/o manually passing the latitude and longitude.
gammastep can retrieve geolocation from geoclue so it works out of the
box for everyone.

replace wlsunset with gammastep

---

.config/ags/modules/sideright/centermodules/wifinetworks.js

Group the networks by ssid and keep max strength for multichannel networks

only keep strongest network by ssid

---

.config/ags/scripts/color_generation/switchwall.sh

this was accidentally dropped in #532

reapply "switchwall: fix transition position for hidpi and multi-monitor"

---

.config/ags/modules/indicators/indicatorvalues.js

fixed volume above 100%

---

.config/ags/modules/.configuration/user_options.js
.config/ags/modules/cheatsheet/keybinds.js
.config/ags/scripts/hyprland/get_keybinds.py

I added the option to change the path to the keybind.conf (since mine is not at the same place).
Also included a check so people get a notification if they entered an incorrect path. `~` in the path now works as well.
The keybindList and keybindListfunc probably be done simpler I just didn't know how.

Keybind path

---

.config/ags/modules/sideleft/tools/changeres.sh
.config/ags/modules/sideleft/tools/quickscripts.js

This pull request introduces a new tool to streamline the process of changing screen resolution. Previously, adjusting screen scaling could result in misalignment or issues with AGS widgets, particularly with high-resolution displays. This tool aims to provide a more reliable method for setting resolutions, which addresses the scaling issues experienced by users with high-resolution screens.

New Tool for Changing Screen Resolution

---

.config/ags/modules/bar/normal/system.js

ags: move datetime polling to Variable

---

.config/ags/scripts/color_generation/generate_colors_material.py

Added fix for GIF wallpaper colorscheme generation!
Now people can set .gif image's as their wallpaper, without bug's.

Support for GIF Wallpapers.

---

arch-packages/illogical-impulse-fonts-themes/PKGBUILD

The AUR package adw-gtk3-git was merged into adw-gtk-theme-git package (closes #743)

Updated adw-gtk3-git package name to adw-gtk-theme-git

---

.config/ags/modules/.configuration/user_options.js
.config/ags/modules/sideleft/apis/booru.js
.config/ags/services/booru.js

save the image and put it in the folder based on the tag

booru: add save image

---

arch-packages/illogical-impulse-hyprland/PKGBUILD
arch-packages/illogical-impulse-portal/PKGBUILD
arch-packages/illogical-impulse-widgets/PKGBUILD
install.sh
scriptdata/installers
scriptdata/options

Switch to stable hyprland related packages (#1080)

---

.config/hypr/hyprland/general.conf

Added active_opacity, inactive_opacity and fullscreen_opacity with defaults as 1. Just wanted to make configuring opacity easier as it is a very popular configuration!

Window opacity in hyprland/general.conf

---

.config/ags/modules/.configuration/user_options.js
.config/ags/modules/sideright/quicktoggles.js
.config/ags/modules/sideright/sideright.js

this module works exactly like this one https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#toggle-animationsbluretc-hotkey 
https://github.com/user-attachments/assets/71e5c38c-7d20-4a59-960c-5b29e1514b8c

[ Module ] Hyprland gamemode

---

.config/ags/modules/sideright/centermodules/wifinetworks.js
.config/ags/scripts/network_scripts/network_bandwidth.py
.config/ags/scss/_sidebars.scss

Pretty useful feature. Also kinda satisfies #675 (not in top bar, but still)

Add network bandwidth tracker to sideright (wifinetworks)

---

.config/ags/modules/sideright/centermodules/wifinetworks.js
.config/ags/scss/_sidebars.scss

Maybe giving it a button to make the password visible isn't necessary, but I think somebody would need or want it, also it makes the widget more proper like a DE
but it's up to you though
(sorry i should rearrange the layout of authEntry)

[Feature] give show password button to wifinetworks

---

Extras/emacs/material-theme.el

Material colors based emacs theme that syncs with wallpaper!
As discussed in #1241 I've made a PR.

Create material-theme.el >> New emacs theme in "Extras/emacs"

---

install.sh

Changed "firstrun" on line 298 to "first run"

Fix spelling mistake in install.sh

---

.config/ags/i18n/locales/Default.json
.config/ags/i18n/locales/fa_IR.json
.config/ags/i18n/locales/fr_FR.json
.config/ags/i18n/locales/it_IT.json
.config/ags/i18n/locales/zh_CN.json
.config/ags/modules/indicators/colorscheme.js
.config/ags/modules/overview/miscfunctions.js
.config/ags/scripts/color_generation/applycolor.sh
.config/ags/scripts/color_generation/colorgen.sh
.config/ags/scripts/color_generation/switchcolor.sh
.config/ags/scripts/templates/gtk/gtk-colors.css
diagnose
scriptdata/installers

As discussed in https://github.com/end-4/dots-hyprland/issues/1261#issuecomment-2849248001
Reduces the size of the python mess we're having
It seems to be already working with minor tweaks, but I'll clean up stuff in the scripts and test on a new account to make sure it works
@clsty you're able to make changes to this branch right?

Replace Gradience with a simpler solution

---

.config/ags/modules/.commonwidgets/notification.js

This PR addresses a notification rendering issue observed in environments like dots-hyprland using ags, where certain notifications, particularly those originating from browsers like Brave or applications like WhatsApp Web, were being displayed with raw HTML content. This included visible tags such as `<a href="...">`, leading to a garbled and unintended display that hinders readability.
`[Notification displaying: <a href="https://web.whatsapp.com/">web.whatsapp.com</a> message]`
To resolve this issue robustly and centrally, the logic within the `processNotificationBody` function has been enhanced. This function, responsible for preparing the notification content before display, now includes a step to actively filter and remove potential HTML tags from the notification body.
A regular …

Fix: Prevent raw HTML rendering in notifications

---

.config/ags/modules/indicators/indicatorvalues.js
.config/hypr/hyprland/keybinds.conf

* Add a keybind for the mute microphone button on the keyboard.
* Make sound muting keybinds really mute the output.
* Display the muted state in the indicator widget.
* Closes #334

Change sound muting behavior

---

update.sh

Make the update script for who want to update in minutes not an hour to rebuild the PKGBUILD again 😐️
I hope it's right

make update.sh script

---

.config/quickshell/services/DateTime.qml

<details>
<summary>Bar</summary>
</details>
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Calendar</summary>
</details>
I think it's ready

DateTime based on system locale

---

.config/quickshell/ii/services/Notifications.qml

Makes notifications not timeout if the expiration timeout is 0
Solves https://github.com/end-4/dots-hyprland/issues/1682
Yes

Do not timeout notification if expiration is 0

---

.config/quickshell/ii/services/HyprlandXkb.qml

This PR enables layout indicator in absence of hl-virtual-keyboard (issue https://github.com/end-4/dots-hyprland/issues/1711).
What’s changed:
- Current active layout is initialized with main keyboard from hyprctl devices instead of targetDevice.
- No targetDeviceName check in activeLayout event to enable multiple keyboard support.
Result:
Me and my friend have working layout indicator.
There may be problems with catching every activeLayout event that I'm now aware of.

Fix: Init layout indicator with main keyboard and update on every activeLayout event (#1711)

---

.config/hypr/hyprlock.conf
.config/matugen/templates/hyprland/hyprlock.conf

What’s changed:
- Layout indicator in hyprlock.
Result:
Working layout indicator in hyprlock.
I think it's ready.

Feature: Hyprlock layout indicator

---

.config/quickshell/ii/modules/background/Background.qml

The following video shows the result of the current implementation:
https://github.com/user-attachments/assets/84bd2e65-090d-422a-9da8-66bd89815a27
Current implementation does not handle extra monitors very well.
However, to fix this, I filter through the workspaces for that current monitor, I then filter through the toplevel windows to find any that are fullscreen while making sure that's for the current active workspace.
This way we only care for the active workspace on that monitor and if it has a fullscreen toplevel window.
I am not sure how to detect if a window is transparent as I feel that would need to be taken in account as well as possible suggestions on refactoring the code if it's not very well structured, with the current documentation, I couldn't see any other way to write …

Fix hiding background when fullscreen

---

.config/quickshell/ii/services/HyprlandData.qml

Changes processes to run hyprctl directly instead of through a bash shell.
Able to be done after fe07298.
yes

Run hyprctl directly in HyprlandData service

---

.config/hypr/hyprland/scripts/workspace_action.sh

The previous script didnt take into account for relative workspaces, and my previous pull request was... bad. 
Added smart branching to detect if the target is a literal number(1,2,90), or a relative number(+1, -20) or a string target. ## 
None. ive been stress testing it since the last 2 
Yes, i believe so.

Feat: Improved Workspace_action.sh and added relative workspace support.

---

.config/quickshell/ii/services/Ai.qml

Added ai policy check during model init
I think it's ready

Feature: Hide online models on local ai policy

---

.config/quickshell/ii/modules/common/Config.qml
.config/quickshell/ii/scripts/colors/switchwall.sh

Adjust terminal harmony
Yes. We can adjust by editing the config json to override harmony values

Customize harmony values for colors from wallpaper
