end-4/dots-hyprland

- README.md
Changed networkmanagerapplet to the correct package name `network-manager-applet` (Arch Linux)
> Fixed typo on network-manager-applet

- README.md
These python dependencies were necessary for me for install `python-material-color-utilities`
> Extend pip install in readme

- README.md
extend readme packages which need to be installed with `cliphist`, required for: `SUPER, V`
> Extend package list

- .config/kitty/kitty.conf
Removing ctrl+c mapping because it overrides the real `CTRL+C` purpose that is used for interrupting blocking processes. In case the mapping in the conf file is enabled, if a process is blocked in the terminal, the user cannot interrupt it and take control of the terminal again. `CTRL + Z` is not enough because the blocking process will run in background. Furthermore, `CTRL+C` does not work on apps running in terminal, like nano or vim.  For this reason I suggest to comment/remove those mappings.
The user can still copy the content in the terminal by the default keybinding that is `CTRL+SHIFT+C` (same for paste by CTRL+SHIFT+V) without specifying any mapping.
> Removing ctrl+c mapping

- .config/dunst/dunstrc
Removing icon_path from dunstrc as requested in https://github.com/end-4/dots-hyprland/pull/19#event-9546981015 because not used.
> Removing icon_path from dunstrc

- .config/eww/scripts/memory
Update script to check or system has swap, if it doesn't it will skip over the calculation to prevent divide by 0 error.
Something else i found, this script only works with locales which uses `.` as decimal separator. Other languages which use a `,` will not work. We could fix this for them by adding `LC_NUMERICAL=en_US.UTF-8` to the script. But i will leave it up to you to decide.
> Update eww/scripts/memory to work without swap

- .config/eww/variables.yuck
Hey there!
I noticed that using just `lsusb` might not guarantee the detection of a mouse. For instance:
```
lsusb                                                
Bus 001 Device 004: ID 0bda:b009 Realtek Semiconductor Corp. Realtek Bluetooth 4.2 Adapter
Bus 001 Device 003: ID 0408:5365 Quanta Computer, Inc. HP TrueVision HD Camera
Bus 001 Device 002: ID 0438:7900 Advanced Micro Devices, Inc. Root Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 0b05:1a94 ASUSTek Computer, Inc. ROG HARPE ACE AIM LAB EDITION
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
The output from `lsusb` doesn't recognize a device with `ID 0b05:1a94` as a mouse. However, if we use `lsusb.py -i`, …
> eww:mousemode - better mouse detection

- .config/eww/scripts/hyprsettings
- .config/eww/windows/osettings.yuck
- .config/eww/windows/winnews.yuck
- .config/hypr/hyprland.conf
- .gitignore
Required by hyprland `v0.28.0` as it moved the blur settings from `decorations` to it's own subcategory, `decorations:blur`
Pardon the stray .gitignore though. I don't know how to only make a PR without it.
> Move blur and it's relevant config paths to subcategory

- .config/ags/windows/bar/system.js
- .config/ags/windows/sideright/sideright.js
why use 'date' if there is a 'GLib.DateTime'?
> remove linux 'date' command from js

- install.sh
Add detection for the existence of OneUI4-icon directory, so that its installation will be skipped if exists when `-f` flag is specified.
Also for consistency.
> Improve OneUI4-icon installation

- .config/hypr/execs.conf
When content copied by Ctrl+C , CJK character becomes `\uxxxx` in `cliphist list`, which reason is actually inside the wl-paste.
You can test this out by adding following to `keybinds.conf` in `~/.config/hypr`:
```conf
bind=,F11,exec, pkill wl-paste && wl-paste --type text --watch cliphist store & wl-paste --type image --watch cliphist store & wl-paste -p --watch wl-copy -p ""
bind=,F12,exec, pkill wl-paste && wl-paste --watch cliphist store & wl-paste -p --watch wl-copy -p ""
```
When you use `F12`, and `Ctrl`+`C` copy this text: `test 测试`, then `cliphist list` in terminal, it becomes `test \u6d4b\u8bd5`.
When you use `F11` (corresponding to the fix included in this PR), and `Ctrl`+`C` copy this text: `test 测试`, then `cliphist list` in terminal, it becomes `test 测试`.
> Fix CJK copied by Ctrl+C became \uxxxx

- .config/ags/widgets/bar/workspaces_hyprland.js
- .config/ags/widgets/overview/overview_hyprland.js
- .config/hypr/keybinds.conf
- .config/hypr/workspace_action.sh
First attempt at JS ... wish me luck :(
This feature will be useful for:
- Users like me who shamelessly opens dozen of workspaces and wants a non-cluttered way of navigating through them. 
- Users having multiple monitors and want to have awesome-wm like experience, where each monitors will have its own set of 10 workspaces.
- Multitaskers who want to context-switch to a different task altogether (like office or personal) and don't want to clutter apps or rearrange workspaces.
This will not affect any functionality for users having workspace <= 10
Description:
- The workspaces will be grouped in a set of 10. If we have 30 workspaces then they will be divided into 3 groups (1-10, 11-20 and 21-30). The current focused group will depend upon the active workspace. If active ws is in between …
> New workflow: Supporting bar and overview for Workspaces > 10

- scriptdata/functions
- scriptdata/installers
These extra lines actually caused errors, but they did not stopped the install script because they're sourced before `set -e`, so that the script still ran without problem.
Anyway, it should be fixed though.
> Remove redundant `cd $(dirname $0)` lines

- .config/ags/data/keyboardlayouts.js
- .config/ags/scss/_osk.scss
- .config/ags/widgets/onscreenkeyboard/onscreenkeyboard.js
- Pressing shift will now cycle between shift, caps lock, and lowercase
- Visual representation of uppercase letters/symbols, as well as AltGr for German keyboards
- You can also add the equivalent Alt keys for QWERTY keyboards, I just don't know what they'd be
- Added German QUERTZ virtual keyboard layout
> On-Screen-Keyboard improvements

- scriptdata/dependencies.conf
I have found that `anyrun` was missing after I ran the script, I had to install it manually and I even had to execute `rustup default stable` in order to install `anyrun`
> 🚀 Add `anyrun` to dependencies.conf

- .config/ags/modules/bar/main.js
This PR fixes the bar corners not appearing in a multi monitor setup (Issue #249 ).
The problem was that the `BarCornerTopleft` and `BarCornerTopright` did not have the monitor id as input.
> fix: Fixed bar corners not appearing on multi monitor setup

- .config/ags/modules/bar/normal/system.js
Grimblast is being called without arguments, resulting in a silent error. Functionality becomes the same like it used to when it used slurp > grim > wl-copy.
> Fix screen snip (grimblast) ags widget

- .config/hypr/custom/env.conf
- .config/hypr/custom/general.conf
- .config/hypr/custom/keybinds.conf
- .config/hypr/custom/rules.conf
- .config/hypr/hyprland/env.conf
- .config/hypr/hyprland/keybinds.conf
- .config/hypr/hyprland/rules.conf
Hyprlang is in use since commit https://github.com/hyprwm/Hyprland/commit/13f6f0b923ff3ec94a3bec886c28b90402ceef91 which changes how comments are parsed. Comments of the type `############# Tearing #############`  or `## Tearing` are no longer valid. This wasn't an observed issue until commit https://github.com/hyprwm/Hyprland/commit/66330281ff19e84c986c5ce639b670929e5dadd6 landed (sourced files weren't taken into consideration till then). 
I just removed any double `#` and added a space after the first `#` on any longer strings. An explanation to this can be found under https://github.com/hyprwm/Hyprland/commit/fae47ef462d1d7969afe001070839391ba6dbaa8. 
Any feedback appreciated.
> hypr: update config files to comply with hyprlang

- .config/ags/scripts/color_generation/switchwall.sh
When using multi-monitors, `swww query | awk -F 'image: ' '{print $2}'` gives N lines, where N is the number of monitors.
As the result, actions `>dark` and `>light` cause AGS styles totally broken.
This commit specifies only the first line to fix the problem.
> Fix `>dark` `>light` actions for multimonitors

- .config/ags/scripts/record-script.sh
If multiple monitors are present, the wf-recorder command will require to select the monitor on stdin. This overcomes that by specifying the monitor on '-o' or '--output' flag.
> Fix full-screen recording for multimonitors

- .config/ags/scripts/color_generation/colorgen.sh
- .config/ags/scripts/color_generation/generate_colors_material.py
- scriptdata/dependencies.conf
Removing dependency [material-color-utilities-python](https://github.com/avanisubbiah/material-color-utilities-python) in favor of [materialyoucolor-python](https://github.com/T-Dynamos/materialyoucolor-python) for picking colors from image, as this [issue](https://github.com/T-Dynamos/materialyoucolor-python/issues/12) is fixed, and the algorithm is [faster](https://github.com/T-Dynamos/materialyoucolor-python/issues/3#issuecomment-1880980050) too.
> Wave goodbye to material-color-utilities-python

- .config/ags/modules/.configuration/user_options.js
- .config/ags/modules/bar/main.js
- .config/ags/modules/bar/normal/spaceleft.js
- .config/ags/modules/indicators/indicatorvalues.js
- .config/ags/modules/indicators/main.js
- .config/ags/services/brightness.js
- install.sh
- scriptdata/dependencies.conf
- uninstall.sh
This implements per-monitor brightness control for **desktops** using [DDC/CI](https://wiki.archlinux.org/title/Backlight#External_monitors). I don't have a laptop to test the current brightnessctl approach, so a new user option is added to choose between brightnessctl and ddcutil.
Ideally, the supported controller for individual monitors should be auto-detected to make use-cases like built-in laptop display + external monitor work. Whoever can test this case may implement it in the future.
> ags: implement per-monitor brightness control

- .config/ags/services/gpt.js
Since a thinking animation is implemented, the "thinking..." string is not necessary anymore. It causes problems displaying answers from chatgpt. My suggestion: Emptying string.
> [Bugfix] Update gpt.js

- .config/ags/modules/sideleft/apis/waifu.js
Since I was confused, why the waifu.js api showed an error after entering various tags (cough* just for research purposes of course), I checked and debugged just to find out, that I just was out of luck with the tags, lol. Always 404.
To prevent confusion I added the notfound state.
> [Feature] Added not found status in waifu.js

- .config/hypr/hyprland/rules.conf
Context menus (Right-Click) of wps office applications are treated like windows and therefore tiled with this rule. This leads to an unwanted snapping of the menu next to the active window.
> Update rules.conf to fix wps office

- .config/ags/modules/cheatsheet/main.js
- .config/ags/modules/onscreenkeyboard/main.js
- .config/ags/modules/onscreenkeyboard/onscreenkeyboard.js
- .config/ags/modules/session/main.js
- .config/ags/modules/session/sessionscreen.js
- .config/ags/scripts/color_generation/switchwall.sh
- .config/hypr/hyprland/keybinds.conf
- scriptdata/dependencies.conf
these widgets were declared for each monitor but never triggered due to:
```
╰─ xrandr --listmonitors
Monitors: 2
0: +DP-1 3840/600x2160/340+0+0  DP-1
1: +DP-2 3840/530x2160/300+7680+0  DP-2
╰─ xrandr --listmonitors | grep -c 'Monitor'
1
```
this pr fixes keybinds and widget implementations for the second monitor
> fix multi-monitor widgets

- update-dots.sh
Automatically updates the Repository and the dots:
Replaces by default .config and .local files in the home directory.
Checks if user has modified files => Asking before replacing modified files. 
You are able to exclude folders from updating.  e.g.  the "custom" folder
Implemented  with Checksums.
> [Feature] Added Update-dots.sh script

- .config/ags/modules/cheatsheet/data_periodictable.js
Renamed Wolfram to Tungsten in the periodic table, Tungsten is the more commonly used name. (Even Wikipedia uses Tungsten https://en.wikipedia.org/wiki/Tungsten)
I was trying to find Tungsten on the table but couldn't find it, ended up wasting me 10 minutes. I am submitting this pr to prevent anyone in the future to suffer the same fate as me.
> Renamed Wolfram to Tungsten in the periodic table

- .config/ags/modules/overview/overview_hyprland.js
Fix a bug in the overview module where the width of window element was not properly truncated.
> fix: truncate if offscreen

- .config/ags/init.js
- .config/ags/modules/.configuration/user_options.js
One may want to use different icon theme for dark and light backgrounds to ensure readability.
This also fixes a race condition by using `Utils.writeFileSync` to ensure the style file is updated before compiling sass.
> ags: use separate symbolic icon theme for different color schemes

- .config/ags/modules/indicators/indicatorvalues.js
The audio popup now works as in most setups and shows up if the volume changes. It does not if you skip a song etc.
I implemented it for backlight as well, but its not working. The hook doesn't trigger if I change the brightness via keybinds. I assume the service doesnt check for that? Didn't check yet.
> Audio popups also showing up if the volume changes e.g. by keys

- .config/ags/modules/bar/normal/system.js
Keep only one digit after the dots on the battery icon.
Before:
After:
> Only show 1 digit after decimal point for battry percentage

- .config/thorium-flags.conf
Updates thorium-flags.conf as `--password-store=gnome` should now be `--password-store=gnome-libsecret` (see https://www.reddit.com/r/archlinux/comments/15sse7i/psa_chromium_dropped_gnomekeyring_support_use/ ) 
I noticed Visual Studio Code automatically changes its flags file to `--password-store=gnome-libsecret` and even edits it if it said `--password-store=gnome` previously, so this would suggest this new flag is probably the recommended one going forward for electron/chromium based apps.
> Update thorium-flags.conf to use gnome-libsecret

- .config/ags/modules/.configuration/user_options.js
Whenever you changed an array in the user_config it threw an error because it would check all the entries with the template user_config and not find the new ones.
Example: `'excludedSites': ["quora.com", "reddit.com"],`
> Arrays in user options don't throw an error anymore

- .config/hypr/hyprland/rules.conf
Two changes to rules.conf:
ADD:
```windowrule=float,title:^(File Upload)(.*)$```
- When browsing the web if there is a prompt to upload a file (like a "browse" or "select file" button) these prompts often come up with a file picker window titled "File Upload" - so they should be floated too.
ADD:
```windowrulev2 = float,title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$```
- When playing back video (e.g YouTube) many browsers (Firefox, Edge, Chrome probably) have a picture in picture mode, currently it is tiled, but it makes much more sense to float it. 
- I tested Firefox (which simply titles its windows "Picture-in-Picture" with no extra info) and Edge (which titles its windows "Picture in picture" with no extra info).
- Hyprland's regex syntax is weird (probs based on C++ modified …
> Window rules fixes/additions

- .config/ags/modules/.configuration/user_options.js
- .config/ags/modules/overview/searchbuttons.js
- .config/ags/modules/overview/windowcontent.js
One bugfix: if the blocked website array is empty there is no `-site:` anymore
And added user options to turn search features on and off.
Also there is a new NoResultsButton (maybe it shouldn't be a button lol) so the search result list is never completly empty.
Also I'm wondering whether the Buttons could be changed so they can also be used when pressing enter, so all the conditions in onAccept could be skipped. Might try some stuff tomorrow (its 3:46am)
> Search customizing

- .config/hypr/hypridle.conf
The dpms off timer is not triggering for me after manually locking the screen via Win+L shortcut, and this commit magically fixes it. It just works, dunno why.
Derived from the example at the bottom of https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/
> hypridle: fix monitor not turning off after manual lock

- arch-packages/illogical-impulse-widgets/PKGBUILD
Hyprlock-git won't build without hyprutils, which is first built in line 141 of `install.sh`:
```bash
v yay $hyprland_installflags --asdeps hyprutils-git hyprlang-git hyprcursor-git hyprwayland-scanner-git
```
This occurs after the hyprlock installation.
[Link to line 141 in install.sh](../blob/main/install.sh#L141)
Is there a reason to keep the installation on line 141 after the change?
> Add Dependency to Build hyprlock-git

- .config/ags/modules/sideright/sideright.js
I installed the dotfiles on OpenSUSE Tumbleweed. When opening the dropdown on the right side of the bar, it wasn't showing me the uptime. Tumbleweed doesn't have "uptime -p" as an option. 
[@nullptroma mentions this issue on the OpenSUSE install discussion](https://github.com/end-4/dots-hyprland/discussions/485#discussioncomment-9394056)
I modified the code, making it attempt to run "uptime -p", and if it fails, it parses the output of "uptime" to display on the panel.
> fixed uptime in AGS sideright module for non-Arch distros

- .config/ags/scripts/hyprland/get_keybinds.py
I tried to make a submap in my config and ags didn't work anymore since the python script couldn't handle the submap rule. This should fix any configs where there is not only keybind rules in the file. Also works with whitespace in front of the line.
Are there any other rules than "bind" that need to be parsed by the script as well?
> get_keybinds.py now only checks for "bind="

- .config/ags/services/booru.js
The +1 is needed so the link doesn't end up with a double slash. Added extensions for JPEG and GIF sources to the regex.
> booru: fix pixiv source link

- .config/ags/modules/.commonwidgets/notification.js
This fixes the following log spam:
```
(com.github.Aylur.ags:2273075): Gjs-CRITICAL **: 11:15:29.279: Object .Ags_Label (0x5f2be6736120), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs. == Stack trace for context 0x5f2be48b33d0 ==
#0   7ffcd01459e0 b   resource:///com/github/Aylur/ags/widgets/label.js:39 (1dcdaf08bb00 @ 10)
#1   5f2be497b5e0 i   file:///home/foobar/.config/ags/modules/.commonwidgets/notification.js:253 (1dcdaf0b72e0 @ 10)
#2   5f2be497b560 i   resource:///com/github/Aylur/ags/utils/timeout.js:14 (1f5daab1150 @ 6)
#3   5f2be497b498 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (1f5daa7d560 @ 139) …
```
> ags: remove timeout source after notification dismissed

- .config/ags/modules/bar/normal/tray.js
For unknown reason, an unknown program (even invisible in D-Spy) occasionally populates an empty tray item of the following properties:
```js
TrayItem {
"category": null,
"id": null,
"title": null,
"status": null,
"window-id": null,
"is-menu": null,
"tooltip-markup": "",
"icon": "image-missing"
}
```
Add a null check for the item id to workaround the issue.
> tray: filter out empty tray items

- .config/ags/modules/overview/overview_hyprland.js
PR for issue #690
The addition of `hpack` to Widget.Revealer seems to fix the horizontal over-expansion issue.
While testing possible fixes, removing `hexpand` from `overview-tasks-workspace` and setting the size of the children also fixed over-expansion, but during animation (such as switching from overview to search results) the unbounded horizontal expansion would trigger and make the animation look bad.
I couldn't find any animation or sizing issues with the `hpack` solution at any scale or size, including very tiny overviews with few windows and large overviews with many windows.
This might not be the "most correct" fix from a math or simplicity perspective, because there might be values somewhere else not being floored or rounded causing the windows inside overview to sometimes …
> overview-tasks-workspace alignment fixes

- .config/ags/modules/.commonwidgets/statusicons.js
- .config/ags/modules/bar/main.js
- .config/ags/modules/bar/normal/spaceright.js
The keyboard layout indicator was only visible on one monitor because there was just one instance of it. I’m not totally sure my fix is the best way to do it, especially since I don't know JavaScript, but it's now visible on all monitors.
> Fix for keyboard layout indicator not showing up on all monitors

- .config/ags/modules/.configuration/user_options.js
- .config/ags/modules/bar/main.js
- .config/ags/variables.js
**Multi-monitor improvement.** 
- Users can now change bar shell mode ("normal", "focus", "nothing") per monitor. That way each monitor can have separate bar look. 
I use it to hide the bar on my second monitor while it stays shown on my main monitor.
I plan to improve this by adding bar monitor config to user_options.js so that selected bar look persists between sessions.
> [Feature] Change shell mode per monitor

- .config/hypr/hyprland/keybinds.conf
Fixes problems with headset media controls, etc.
> Add 'XF86AudioPrev' & 'XF86AudioPause' bindings.

- .config/ags/modules/onscreenkeyboard/onscreenkeyboard.js
- .config/hypr/hyprland/keybinds.conf
- .local/bin/fuzzel-emoji
* `--no-fuzzy` has been replaced by `--match-mode` in fuzzel
see commit [a778de2e56](https://codeberg.org/dnkl/fuzzel/commit/a778de2e56a894591dc55cd103a98b019dfec5ed)
> replace `--no-fuzzy` with `--match-mode fzf`

- .config/ags/modules/overview/overview_hyprland.js
This prevents the application overview from throwing an error when multiple monitors are plugged in but only one is enabled.
> Array boundary Check for Overview

- .config/hypr/hyprland/general.conf
- .config/hypr/hyprland/rules.conf
Updated hyprland today and noticed that I was getting an error/red error message at the top of the screen as I had `no_gaps_when_only = 1` uncommented in the dwindle config section of `general.conf`
Turns out that setting has been removed, and the new method to achieve this setting is using workspace rules.
The rules I added were taken from a recent update to the Hyprland default/example config (https://github.com/hyprwm/Hyprland/commit/8e51a36c7fd500e865e34f08ab4dc4331dca59cf). Since there don't seem to be any existing workspace rules, I added a section for them to the rules file, and then added the example code verbatim (with one extra comment line explaining that it replaces the old dwindle config setting).
As the `no_gaps_when_only = 1` is commented out in the current dots-hyprland …
> Move dwindle config "no gaps when only" to workspace rules

- arch-packages/illogical-impulse-ags/PKGBUILD
- arch-packages/illogical-impulse-gnome/PKGBUILD
- arch-packages/illogical-impulse-microtex-git/PKGBUILD
* our ags configuration uses the bluetooth module so it can't start w/o gnome-bluetooth-3.0
* gammastep is used by ags sidebar and irrelevant to gnome
> move gnome-bluetooth-3.0 and gammastep to ags dependencies

- .config/ags/modules/.commonwidgets/statusicons.js
Wifi Indicator: currently, there is no indication when wifi is off (and 'wifi_off' icon is used to show disconnected status). I added a check for it and added appropriate icon for 'wifi_disconnected'.
Bluetooth Indicator: added an additional check to show 'bluetooth_connected' icon.
> status icons: add 'wifi disconnected' and 'bluetooth connected' icons

- .config/foot/foot.ini
```
$ man foot.ini
```
```
SECTION: text-bindings
This section lets you remap key combinations to custom escape sequences.
The  format is text=combo1...comboN. That is, the string to emit may have one or
more key  combinations,  space  separated.  Each  combination  is  in  the  form
mod1+mod2+key.  The  names  of  the  modifiers and the key must be valid XKB key
names.
The text string specifies the characters, or bytes, to emit when the  associated
key combination(s) are pressed. There are two ways to specify a character:
•   Normal, printable characters are written as-is: abcdef.
•   Bytes  (e.g.  ESC)  are  written as two-digit hexadecimal numbers, with a \x
prefix: \x1b.
Example: you would like to remap Super+k to the Up key.
The escape sequence for the Up key is ESC [ A (without  the …
```
> Fix Control+Shift+C not working in the latest foot terminal

- .config/hypr/hyprland/rules.conf
This PR updates the configuration to use the new v2 syntax exclusively. The old v1 syntax was causing invalid rule errors. All window rules now use windowrulev2 with explicit fields (e.g. class:, title:, floating:) as per the latest Hyprland documentation.
This change fixes the syntax issue and ensures the configuration is compatible with the current Hyprland version.
(I will note, this change was partially aided with ChatGPT reasoning; But this has been tested to be working very well.)
> Pull Request: Fix Window Rules Syntax for v2

- arch-packages/illogical-impulse-agsv1/PKGBUILD
- arch-packages/illogical-impulse-oneui4-icons-git/PKGBUILD
This PR addresses the TypeScript build error (TS18047) caused by possible null `raw` buffer in greetd.ts.
- Added null checks on `get_data()` results.
- Now builds successfully via `makepkg`.
Tested on: Arch Linux (Hyprland)
Note: I know I cannot update the PKGBUILD, and this should update ```./illogical-impulse-agsv1/src/ags-1.9.0/src/service/greetd.ts```, but I cannot update that because the code will be overwritten when I run ```makepkg -si```
<details>
<summary>Proposed Fix for greetd.ts</summary>
```typescript
import App from '../app.js';
import Service from '../service.js';
import GLib from 'gi://GLib';
import Gio from 'gi://Gio';
Gio._promisify(Gio.InputStream.prototype, 'read_bytes_async');
const SOCK = GLib.getenv('GREETD_SOCK');
type Request = {
create_session: {
username: …
```
> Fix PKGBUILD: greetd.ts build error (TS18047)

- .config/ags/modules/sideleft/apis/waifu.js
The async function getImageViewerApp return void as it doesn't return anything from the function instead only returning from within the promise.
This fix allows the "Waifu" tab to open image in an external viewer.
I have tested this locally and have verified that it now functions as expected.
> Fixes the function getImageViewerApp

- install.sh
i was trying to install it on archlinuxarm
this patch enables the installation via `install.sh` script on non-x86 devices
i confirmed that all packages can be built under aarch64 without modification
> fix: add -A to makepkg

- .config/ags/modules/bar/normal/spaceleft.js
If there aren't any opened windows, title widget displays "workspace 2", but if you switch between opened workspaces without opening any windows, this title doesn't change
In this fix, I added a hook to update this widget also when workspace number changes
(I didn't add hook on top title, because it won't change in this case anyway)
> Fix title on workspace change

- .config/ags/modules/.configuration/default_options.jsonc
- .config/ags/modules/dock/dock.js
I have scratchpads and i didn't want them to appear in the dock so i added this
For example i put 
```jsonc
"ignoredAppsRegex": ["^kitty-dropterm-.$"],
```
so it will ignore all app clases that match kitty-dropterm-.
> Add option to ignore certain apps in dock

- .config/ags/scripts/color_generation/applycolor.sh
- .config/ags/scripts/templates/fuzzel/fuzzel.theme
- .config/fuzzel/fuzzel.ini
Instead of overwriting the entire fuzzel.ini on each theme change. Theme changes are made to `fuzzel.theme` which is then imported by `fuzzel.ini`
Rationale:
I like to use vim binds for fuzzel and there wasn't a good way to modify `fuzzel.ini` without making the end-4 update process complicated.
If you're okay with this, I'll make another PR for ii-qs
> Allow fuzzel.ini to be customized

- README.md
as fish is a non-posix-compliant shell, it doesn't support bash syntax like bash <(), so i have changed the url to one that fish shell supports.
btw, sorry i haven't tested this yet. please test the script before merging it should work fine, but just in case.
> chore: add fish shell compatible setup link

- .config/zshrc.d/dots-hyprland.zsh
Recently upgraded from ags to quickshell and the terminal colors werent syncing with wallpaper i put
the source file from ~/.config/zshrc.d/dots-hyprland.zsh wasnt working since it was using the outdated ags generated cache.
Removed the ags one and added the quickshell color gen
Now it works perfectly
> Fixed Terminal Color generation bug for quickshell

- .config/quickshell/modules/bar/Bar.qml
1. Fixed visibility consistency: Corner round decorators now properly hide when `showBackground` is false
2. Fixed transparency consistency: Corner round decorators now use the same transparency value with the main bar
- Before: 
- After:
Ready, at least it looks good on the surface.
> Bar.qml: Fix round decorators transparency and visibility consistency with bar

- .config/quickshell/scripts/colors/switchwall.sh
Update color.txt path in switchwall.sh -
The rest of the codebase uses "$STATE_DIR/user/generated/color.txt", apart from one line in the switchwall script which still uses "$STATE_DIR/user/color.txt".
Assume this is just a typo?
> Update color.txt path in switchwall.sh

- .config/quickshell/ii/services/Ai.qml
The messages were not preserved and passed to further calls outside of the reasoning part.
Append the newContent string to rawContent, just like it is appened to the regular content.
Pretty much I think.
> fix(ai): add the full received message to rawContent (OpenAi format)

- update.sh
This change enhances the `update.sh` script to better handle conflicts with user-modified configuration files.
When a file conflict occurs during an update, it's often because the user has intentionally made personal modifications that they want to keep. When prompted to resolve a conflict, the user can now select "7) Add to ignore and skip". This action appends the file's path to the update ignore list, preventing it from being overwritten in all future updates.
Ready for review. Feedback is welcome
> feat: add option to ignore conflicting files

- .config/quickshell/ii/modules/overview/Overview.qml
- .config/quickshell/ii/modules/overview/SearchWidget.qml
This PR fixes a behavior bug in the clipboard history (issue #1690):  
When the clipboard content changes, the clipboard history ListView would sometimes scroll to the bottom, showing the oldest entry instead of the most recent one.
**What’s changed:**
- In `.config/quickshell/ii/modules/overview/SearchWidget.qml`, the ListView now always scrolls to the top (first entry) when the clipboard history model changes in clipboard mode.
- This is done by setting `currentIndex = 0` and calling `positionViewAtIndex(0, ListView.Beginning)` after the model updates.
**Result:**  
The clipboard history now consistently shows the most recent entry at the top, even after cut/copy or other clipboard changes.
---
- Yes, this is ready for review and merge.
- Feedback welcome if there are edge cases I …
> Fix: Always scroll clipboard history to top when content changes (#1690)

- .config/quickshell/ii/modules/bar/UtilButtons.qml
- .config/quickshell/ii/modules/common/Config.qml
- .config/quickshell/ii/modules/settings/InterfaceConfig.qml
Adds a power profile toggle to the topbar, using PowerProfiles from quickshell and power-profiles-daemon
Disabled by default
I didn't encounter any bug while testing and it's a pretty simple feature.
I don't really like the js `switch`es in the click event, but as it's a 3-options toggle I didn't really see a better way to implement it, please lmk if I should change that.
> feat: power-profile switcher in topbar

- .config/quickshell/ii/services/Notifications.qml
This fixes #1465 where notifications become empty if the source application (Betterbird, Vesktop and Ferdium in my case) closes the notification before interacting with it in the shell.
I used **onNotificationChanged** handler to detect when the notification property becomes null (which happens when the underlying object is destroyed). When this occurs, it triggers root.discardNotification(), so the empty notification does not appear.
I think it is ready for review, as I haven't received empty notifications anymore (at least from the problematic apps I mentioned before).
> Fix empty notifications

- .config/hypr/hyprland/env.conf
- .config/hypr/hyprland/keybinds.conf
- .config/hypr/hyprland/scripts/launch_first_available.sh
Allow us to override the terminal app. Some of us really don't like kitty.
To use, set the env var `TERMINAL` to terminal of your choice, either in hyprland `env.conf` or via whatever script runs before your desktop is initialized.
Yes
> Overrideable default terminal app

- .config/hypr/hyprland/keybinds.conf
Escape terminal env for keybinds
Addresses improper env substitution raised in: #1753
Yes
> Addresses improper env substitution for terminal launch

- .config/quickshell/ii/modules/bar/BarContent.qml
- .config/quickshell/ii/modules/verticalBar/VerticalBarContent.qml
- .config/quickshell/ii/services/HyprlandXkb.qml
In the top-right bar, the keyboard layout did not accurately change when also providing a variant.
Here is an example of a keyboard setup where nothing happened before:
```
kb_layout = us,ro
kb_variant = ,std
kb_options = grp:shifts_toggle
```
In this case, pressing both shift keys would cause the layout to change, allowing for the input of Romanian characters. However, in the top right, "us" will still be displayed.
The fix is supposed to handle the layout + variant case.
Just see if you like it :)
> bar: fixed kb layout+variant display in top right

- .config/quickshell/ii/modules/overview/OverviewWidget.qml
It happens with laptop linked with external monitors, and there are monitors disabled by Hyprland.
This fixed OvervideWidget cannot get correct 'monitors' in multi-monitors setup.
Tested case:
```
[{
"id": 1,
"name": "DP-2",
"description": "HKC OVERSEAS LIMITED G24H1 0000000000001",
"make": "HKC OVERSEAS LIMITED",
"model": "G24H1",
"serial": "0000000000001",
"width": 1920,
"height": 1080,
"refreshRate": 200.00000,
"x": 0,
"y": 0,
"activeWorkspace": {
"id": 3,
"name": "3"
},
"specialWorkspace": {
"id": 0,
"name": ""
},
"reserved": [0, 40, 0, 0],
"scale": 1.00,
"transform": 0,
"focused": true,
"dpmsStatus": true,
"vrr": true,
"solitary": "0",
"activelyTearing": false,
"directScanoutTo": "0",
"disabled": false,
"currentFormat": "XRGB8888",
"mirrorOf": "none",
"availableModes": …
```
> Fix various issues of overview with multiple monitors setup

- .config/quickshell/ii/modules/common/functions/Session.qml
hyprland's main process name has been changed from Hyprland to hyprland (all lower-case).
> fix: ignore case (The latest Hyprland process name has changed)
